# This file hepls define board specific paths for the mbed SDK libarary
# Currently it is simplistic to allow development on the discovery & K64F boards

#==========================    VARIABLS    	   ==========================#

TARGET_ARCH := CORTEX_M
TARGET_PREFIX := TARGET_
TOOLCHAIN_PREFIX := TOOLCHAIN_GCC
ARM_POSTFIX := _ARM
DRIVERS := drivers
HAL := hal
PLATFORM := platform
TARGETS := targets
CMSIS := cmsis
DEVICE := device
TARGET_CORTEX := TARGET_CORTEX

#========================== BAORD specific     ==========================#


#------------------------- discovery board    ---------------------------#

ifeq ($(BOARD), DISCO_F407VG)

	# setup paths

	BOARD_VENDOR := STM
	BOARD_LINE := STM32F4
	BOARD_MCU  := STM32F407xG

	BOARD_PATHS += $(BOARD_VENDOR)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)/$(TOOLCHAIN_PREFIX)$(ARM_POSTFIX)

	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(TARGET_PREFIX)$(BOARD)
	# setup directives

	CC_DIRECTIVES = -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 \
	-DDEVICE_PORTOUT=1 -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 \
	-DTOOLCHAIN_object -DTARGET_STM32F4 -D__CMSIS_RTOS -DTOOLCHAIN_GCC \
	-DDEVICE_I2C_ASYNCH=1 -DTARGET_CORTEX_M -DTARGET_STM32F407xG \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 \
	-DTARGET_UVISOR_UNSUPPORTED -DDEVICE_SPI_ASYNCH=1 -DDEVICE_SERIAL=1 \
	-DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 \
	-DTRANSACTION_QUEUE_SIZE_SPI=2 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 \
	-DTARGET_FAMILY_STM32 -DTARGET_DISCO_F407VG -DDEVICE_PORTIN=1 -DTARGET_RELEASE \
	-DTARGET_STM -DTARGET_STM32F407 -DTARGET_STM32F407VG -DTARGET_LIKE_MBED \
	-D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 \
	-DUSB_STM_HAL -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_PWMOUT=1 \
	-DARM_MATH_CM4 -DRTC_LSI=1

	CXX_DIRECTIVES = -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 \
	-DDEVICE_PORTOUT=1 -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 \
	-DTOOLCHAIN_object -DTARGET_STM32F4 -D__CMSIS_RTOS -DTOOLCHAIN_GCC \
	-DDEVICE_I2C_ASYNCH=1 -DTARGET_CORTEX_M -DTARGET_STM32F407xG \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 \
	-DTARGET_UVISOR_UNSUPPORTED -DDEVICE_SPI_ASYNCH=1 -DDEVICE_SERIAL=1 \
	-DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 \
	-DTRANSACTION_QUEUE_SIZE_SPI=2 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 \
	-DTARGET_FAMILY_STM32 -DTARGET_DISCO_F407VG -DDEVICE_PORTIN=1 \
	-DTARGET_RELEASE -DTARGET_STM -DTARGET_STM32F407 -DTARGET_STM32F407VG \
	-DTARGET_LIKE_MBED -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 \
	-DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 -DUSB_STM_HAL -DDEVICE_SPISLAVE=1 \
	-DDEVICE_ANALOGIN=1 -DDEVICE_PWMOUT=1 -DARM_MATH_CM4 -DRTC_LSI=1


	ifeq ($(BOOTLOADER), 1)
	#Size Allocated for Bootloader if change this also need to change FLASH addr
	# in Linker Script to be 0x08000000 + BOOTLOADER_RESERVED_SIZE
	BOOTLOADER_RESERVED_SIZE := 0x20000
	#LINKER_SCRIPT := STM32F407XG.ld
	CC_DIRCTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	CXX_DIRECTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	endif

#-------------------------    K64F board    ---------------------------#


else ifeq ($(BOARD), K64F)

	BOARD_VENDOR := Freescale
	BOARD_LINE := MCUXpresso_MCUS
	BOARD_MCU  := MCU_K64F
	FRDM := FRDM

	BOARD_PATHS = $(BOARD_VENDOR)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/api
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)/$(TOOLCHAIN_PREFIX)$(ARM_POSTFIX)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/drivers
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(TARGET_PREFIX)$(FRDM)

	CC_DIRECTIVES := -DFEATURE_LWIP=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 \
	-DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_LOWPOWERTIMER=1 \
	-DDEVICE_RTC=1 -DTOOLCHAIN_object -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED \
	-DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DTOOLCHAIN_GCC -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED \
	-DTARGET_K64F -DDEVICE_SPI_ASYNCH=1 -DDEVICE_PWMOUT=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX \
	-DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 \
	-DCPU_MK64FN1M0VMD12 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE \
	-DTARGET_RELEASE -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DDEVICE_TRNG=1 \
	-D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DTARGET_FRDM \
	-DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 \
	 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4

	CXX_DIRECTIVES := -DFEATURE_LWIP=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 \
	-DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7=0 -DDEVICE_LOWPOWERTIMER=1 \
	-DDEVICE_RTC=1 -DTOOLCHAIN_object -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED \
	-DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DTOOLCHAIN_GCC -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED \
	-DTARGET_K64F -DDEVICE_SPI_ASYNCH=1 -DDEVICE_PWMOUT=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX \
	-DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 \
	-DCPU_MK64FN1M0VMD12 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE \
	-DTARGET_RELEASE -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DDEVICE_TRNG=1 \
	-D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DTARGET_FRDM \
	-DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 \
	-DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4

	ifeq ($(BOOTLOADER), 1)
	#Size Allocated for Bootloader if change this also need to change FLASH addr
	# in Linker Script to be 0x08000000 + BOOTLOADER_RESERVED_SIZE
	BOOTLOADER_RESERVED_SIZE := 0x20000
	#LINKER_SCRIPT := FRDM-K64F-bootloader.ld
	CC_DIRCTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	CXX_DIRECTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	endif

#-------------------------    EVAL board    ---------------------------#-

else ifeq ($(BOARD), EVAL_F469NI)
	# setup paths

	BOARD_VENDOR := STM
	BOARD_LINE := STM32F4
	BOARD_MCU  := STM32F469xI

	BOARD_PATHS += $(BOARD_VENDOR)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)
	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(DEVICE)/$(TOOLCHAIN_PREFIX)$(ARM_POSTFIX)

	BOARD_PATHS += $(BOARD_VENDOR)/$(TARGET_PREFIX)$(BOARD_LINE)/$(TARGET_PREFIX)$(BOARD_MCU)/$(TARGET_PREFIX)$(BOARD)
	# setup directives

	CC_DIRECTIVES :=  -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DDEVICE_PORTOUT=1 \
	-DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DTOOLCHAIN_object -DTARGET_STM32F4 \
	-D__CMSIS_RTOS -DTOOLCHAIN_GCC -DDEVICE_I2C_ASYNCH=1 -DTARGET_CORTEX_M -DTARGET_STM32F469xI \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED \
	-DDEVICE_SPI_ASYNCH=1 -DDEVICE_SERIAL=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 \
	-DTRANSACTION_QUEUE_SIZE_SPI=2 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DTARGET_FAMILY_STM32 \
	-DTARGET_EVAL_F469NI -DDEVICE_SLEEP=1 -DDEVICE_PORTIN=1 -DTARGET_RELEASE -DTARGET_STM \
	-DTARGET_STM32F469 -DTARGET_STM32F469NI -DTARGET_LIKE_MBED -D__MBED_CMSIS_RTOS_CM \
	-DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 -DUSB_STM_HAL -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 \
	-DDEVICE_PWMOUT=1 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_STM32469I_EVAL \
	-DUSE_IOEXPANDER -DDEVICE_TRNG=1 -DDEVICE_LOWPOWERTIMER=1 -DDEVICE_FLASH=1

	CXX_DIRECTIVES := -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DDEVICE_PORTOUT=1 \
	-DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DTOOLCHAIN_object -DTARGET_STM32F4 \
	-D__CMSIS_RTOS -DTOOLCHAIN_GCC -DDEVICE_I2C_ASYNCH=1 -DTARGET_CORTEX_M -DTARGET_STM32F469xI \
	-DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED \
	-DDEVICE_SPI_ASYNCH=1 -DDEVICE_SERIAL=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DDEVICE_I2C=1 \
	-DTRANSACTION_QUEUE_SIZE_SPI=2 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DTARGET_FAMILY_STM32 \
	-DTARGET_EVAL_F469NI -DDEVICE_PORTIN=1 -DTARGET_RELEASE -DTARGET_STM -DTARGET_STM32F469 \
	-DTARGET_STM32F469NI -DTARGET_LIKE_MBED -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 \
	-DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 -DUSB_STM_HAL -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 \
	-DDEVICE_PWMOUT=1 -DARM_MATH_CM4 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_STM32469I_EVAL \
	-DUSE_IOEXPANDER -DDEVICE_TRNG=1 -DDEVICE_LOWPOWERTIMER=1 -DDEVICE_FLASH=1


	ifeq ($(BOOTLOADER), 1)
	#Size Allocated for Bootloader if change this also need to change FLASH addr
	# in Linker Script to be 0x08000000 + BOOTLOADER_RESERVED_SIZE
	BOOTLOADER_RESERVED_SIZE := 0x20000
	CC_DIRCTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	CXX_DIRECTIVES += -DVECT_TAB_OFFSET=$(BOOTLOADER_RESERVED_SIZE)
	endif

else
$(error [ERROR]: Configurations for <$(BOARD)> has not been added. Currently Supports: [EVAL_F469NI, K64F, DISCO_F407VG]  Please add it in Board.mk file)
endif
